statefile: tv.state
defaultlist: dbcart
storage:
        - defaults/
        - /media/pub/Movies/
calendar: http://newradio/moviesched/publish.php/moviesched.ics
timezone: America/New_York
directoryscan:
    include:
        - \.(?:avi|m4v|mpe?g|mkv|ogg|ogm)$
    exclude: 
        - \(noauto\)
player: Mplayer
#player_conf:
#    host: radio
