statefile: tv.state
defaultlist: defaults/masterdefault.lst
storage:
        - /mnt/server/pub/Music/
        - ./defaults/
calendar: http://newradio/radiosched/publish.php/radiosched.ics
timezone: America/New_York
directoryscan:
    include: 
        - \.(?:mp3|wave?)$
    exclude: 
        - \(noauto\)
player: MPD
player_conf:
    host: radio
