requires 'POE';
requires 'YAML';
requires 'Data::ICal';
requires 'LWP::UserAgent::POE';
requires 'DateTime';
requires 'DateTime::Format::ISO8601';
requires 'Audio::MPD';
requires 'Sereal';
requires 'Feature::Compat::Try';
